.TH man 1 "21 Apr 2018" "0.1.2" "simplify man page"
.SH NAME
simplify - put a mathematical expression into it's simplest terms.
.\"
.SH SYNOPSIS
man [\fB\-v\fR\] [\fB\-q\fR\] [\fB\-f\fR\ FILE] [\fB\-i\fR\ VARIABLE] [\fB\-d\fR\ VARIABLE=EXPRESSION] ...EXPRESSION
.\"
.SH DESCRIPTION
.B simplify
.\"
Simplify is a simple utility to evaluate a mathematical expression.
It supports a wide range of operations, and it work around unknown variables.

.SH OPTIONS
.TP
.BR \-v ", "\-\-verbose
show status updates.
.\"
.TP
.BR \-q ", " \-\-quite
don't print anything but errors.
.\"
.TP
.BR \-f ", " \-\-file \=FILE
evaluate FILE before the expression arguments.
.\"
.TP
.BR \-i ", " \-\-isolate \=VARIABLE
attempt to isolate VARIABLE on one side of an assignment or equality operator.